CREATE TABLE experiences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position        VARCHAR(255)                            NOT NULL,
    additional_info TEXT,
    start_date      date                                    NOT NULL,
    end_date        date,
    company_id      BIGINT                                  NOT NULL,
    student_id      UUID                                    NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_experiences PRIMARY KEY (id)
);
