CREATE TABLE skills
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(128),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    student_id UUID,
    speciality_id BIGINT,
    CONSTRAINT pk_skills PRIMARY KEY (id)
);

