CREATE TABLE education
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institution     VARCHAR(255)                            NOT NULL,
    additional_info TEXT,
    web_url         VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_education PRIMARY KEY (id)
);
