CREATE TABLE institution
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_year   INTEGER                                 NOT NULL,
    end_year     INTEGER                                 NOT NULL,
    education_id BIGINT                                  NOT NULL,
    student_id   UUID                                    NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_institution PRIMARY KEY (id)
);
