CREATE TABLE requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id      VARCHAR(16),
    result       VARCHAR(16)                             NOT NULL,
    chat_url     VARCHAR(255),
    recruiter_id UUID                                    NOT NULL,
    student_id   UUID                                    NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_RECRUITER FOREIGN KEY (recruiter_id) REFERENCES recruiters (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);