ALTER TABLE institution
    ADD CONSTRAINT FK_INSTITUTION_ON_EDUCATION FOREIGN KEY (education_id) REFERENCES education (id);

ALTER TABLE institution
    ADD CONSTRAINT FK_INSTITUTION_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);
